bootrr-generic-tests: Add test for online cpus
kernelci/bootrr pull request #11
Opened 2021-05-28 15:24 UTC by 10ne1

This test uses the generic cpu topology information from
sysfs to determine if all cpus have been succesfully brought
up for use.

Signed-off-by: Adrian Ratiu <adrian.ratiu@collabora.com>

See [here](https://lava.collabora.co.uk/scheduler/job/3893271#results_145763437) an example failure caught by this test on a Renesas R-Car board with the secondary cpu cluster offline.

2021-05-28 15:28 UTC, 10ne1 commented
For some reason I cannot add reviewers. FYI: @gctucker and @eballetbo if you wish to review :smile:

2021-05-28 16:26 UTC, eballetbo requested changes
Some few changes

2021-05-28 16:26 UTC, eballetbo commented on helpers/bootrr-generic-tests
> +test_cpu_bringup() {
To be more coherent with current layout, I'd add this test in a separate assert_cpu_bringup file following the same schema as others, and here just call 

assert_cpu_bringup 

If we start to add generic functions for tests here, this file can end up unreadable.

2021-05-28 16:26 UTC, eballetbo commented on helpers/bootrr-generic-tests
> +test_cpu_bringup() {
Apart from this, the test LGTM. But did you try with a kernel that has CONFIG_SMP=n? It is a common configuration on different build. I'm wondering if this just passes or give us a false positive.

2021-05-28 17:24 UTC, 10ne1 commented on helpers/bootrr-generic-tests
> +test_cpu_bringup() {
Thanks for the review. I tried on non SMP systems, SMP with working or failing CPUs and SMP with CONFIG_SMP=n. In all cases the results were as expected. i.e. no false positives.

Will update the review to add the `assert_cpu_bringup`.

2021-05-31 13:26 UTC, eballetbo approved these changes
LGTM

2021-05-31 22:19 UTC, gctucker commented
OK let's get the baseline rootfs rebuilt to have it tested on staging, I'll look into this tomorrow as it's not done automatically (yet).

2021-06-02 09:12 UTC, gctucker commented
This is getting built now, will check again later if it worked.

2021-06-03 11:58 UTC, 10ne1 commented
@gctucker did it work? :)

2021-06-03 14:15 UTC, gctucker commented
@mgalka Is on the case now.  The Jenkins jobs to create buildroot images is a bit flaky.

2021-06-22 21:50 UTC, gctucker commented
@mgalka Please check whether this is working as expected now on staging with links to results on the web dashboard.  If that's the case, then I believe this can be merged and the production rootfs images can be updated.

2021-06-23 13:56 UTC, mgalka commented
There are jobs being run on staging with baseline.bootrr.all-cpus-are-online test enabled.

https://staging.kernelci.org/test/plan/id/60d2bc2986cd8721d724bf59/
https://staging.kernelci.org/test/case/id/60d2bc2986cd8721d724bf61/

Everything looks good.

2021-06-23 18:32 UTC, merged